# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Code Journey"
description: > # this means to ignore newlines until "email:"
   Blogging Software Development topics that would've made my life easier if it existed.

email: robindalmy@gmail.com
#blog logo
logo: "/assets/images/robin-bird-300px.jpg"
float_logo: true # true, false (default)
google_analytics: true

# blog cover
cover: "/assets/images/cover-image.jpg"

name: 'Robin Tubungbanua'
author: 'Robin Tubungbanua'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://blog.robindalmy.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@robindalmy'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/robindalmy
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mistermunchkin
    desc:	Not much going on here
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
